# Setup
title:               Ahmad Badary
tagline:             'Main Page'
description:         'A place where I deploy my projects and ideas, and scribble my notes.<br /> Made by <a href="https://www.linkedin.com/in/" target="_blank">@Ahmad-Badary</a>.'
gems: [jekyll-paginate]
# paginate: 5
# paginate_path: "page:num"
exclude: [node_modules]

# About/contact
author:
  name:              Ahmad Badary
  url:               https://ahmedbadary.github.io/
  email:             badary.ahmad@gmail.com
  github:            https://github.com/AhmedBadary/
  facebook:          https://www.facebook.com/
github_username:      AhmedBadary
linkedin_username:    /
facebook_username:    /


# Gems
gems:
  # - jekyll-paginate

#Others
markdown: kramdown

port: 8889

# gems: [jekyll-paginate]
# paginate: 5
# paginate_path: "page:num"

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Custom vars
version:             1.0.0

exclude: [vendor]
